name: ci
on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install deps
        run: npm install
      - name: Run tests
        run: npm test
  
  cd:
    runs-on: ubuntu-latest
    needs: ci
    if: github.ref == 'refs/heads/main'
    steps:
      - name: SSH login
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: | 
            cd ~/se2/16/se2-example-backend
            git reset --hard origin/main
            git clean -dxf
            git pull https://${{ secrets.CLONE_TOKEN }}@github.com/lightspot21/se2-example-backend main
            bash -ci 'npm install'
            bash -ci 'pm2 restart example-backend-16'
